<wsdl:definitions
     name="signIn"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callAccountService/signIn"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callAccountService/signIn"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:msg_in_out="http://xmlns.oracle.com/bpel_process/callAccountService/signIn"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="signIn_plt" >
    <plt:role name="signIn_role" >
      <plt:portType name="tns:signIn_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/bpel_process/callAccountService/signIn" schemaLocation="../Schemas/signIn.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Body_msg_in">
        <wsdl:part name="Body" element="msg_in_out:Body"/>
    </wsdl:message>
    <wsdl:message name="GetResponse_msg_out">
        <wsdl:part name="GetResponse" element="msg_in_out:GetResponse"/>
    </wsdl:message>
    <wsdl:portType name="signIn_ptt">
        <wsdl:operation name="signIn">
            <wsdl:input message="tns:Body_msg_in"/>
            <wsdl:output message="tns:GetResponse_msg_out"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
