<wsdl:definitions
     name="checkWarehouse"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callNewOrderService/checkWarehouse"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callNewOrderService/checkWarehouse"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:msg_in_out="http://xmlns.oracle.com/bpel_process/callNewOrderService/checkWarehouse"
    >
  <plt:partnerLinkType name="Request_Response_plt" >
    <plt:role name="Request-Response_role" >
      <plt:portType name="tns:Request_Response_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/bpel_process/callNewOrderService/checkWarehouse" schemaLocation="../Schemas/checkWarehouse.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Body_msg_in">
        <wsdl:part name="Body" element="msg_in_out:Body"/>
    </wsdl:message>
    <wsdl:message name="GetResponse_msg_out">
        <wsdl:part name="GetResponse" element="msg_in_out:GetResponse"/>
    </wsdl:message>
    <wsdl:portType name="Request_Response_ptt">
        <wsdl:operation name="Request-Response">
            <wsdl:input message="tns:Body_msg_in"/>
            <wsdl:output message="tns:GetResponse_msg_out"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
