<wsdl:definitions
     name="getAllBranch"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callBranchService/getAllBranch"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/http/bpel-process/callBranchService/getAllBranch"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:msg_in_out="http://xmlns.oracle.com/bpel_process/callBranchService/getAllBranch"
    >
  <plt:partnerLinkType name="getAllBranch_plt" >
    <plt:role name="getAllBranch_role" >
      <plt:portType name="tns:getAllBranch_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/bpel_process/callBranchService/getAllBranch" schemaLocation="../Schemas/getAllBranch.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Body_msg_in">
        <wsdl:part name="Body" element="msg_in_out:Body"/>
    </wsdl:message>
    <wsdl:message name="GetResponse_msg_out">
        <wsdl:part name="GetResponse" element="msg_in_out:GetResponse"/>
    </wsdl:message>
    <wsdl:portType name="getAllBranch_ptt">
        <wsdl:operation name="getAllBranch">
            <wsdl:input message="tns:Body_msg_in"/>
            <wsdl:output message="tns:GetResponse_msg_out"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
